services:
  - type: web  # Must be 'web' for dynamic web services
    name: expense-manager-frontend  # Replace with your service name
    runtime: node  # Use Node.js runtime for building the React app
    buildCommand: npm install && npm run build  # Build command for React
    startCommand: npx serve -s build  # Serve the built React app statically

    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://expensemanager4.azurewebsites.net  # Replace with your backend API

    branch: main  # Branch to deploy from

